### ISSUE TITLE
uhhhh....

### ISSUE THREAD

**Issue by MesaBlack** [MontagueM/DestinyOracle#1]
![image](https://github.com/MontagueM/DestinyOracle/assets/132141735/7b062cbd-34af-4e9e-9a99-5eb1ac136c83)

**Comment by MontagueM** [comment]
lol

**Comment by MontagueM** [comment]
removed links

**Comment by MesaBlack** [comment]
why?

**Comment by MesaBlack** [comment]
![image](https://github.com/MontagueM/DestinyOracle/assets/132141735/c2fd3ab5-8064-4c13-8f3b-2bcca1aead56)

**Comment by MesaBlack** [comment]
second try after confirmation
